#!/bin/bash
aseqdump -p "nanoKONTROL" | \
while IFS=" ," read src ev1 ev2 ch label1 data1 label2 data2 rest; do
    case "$ev1 $ev2 $data1 $data2" in
        "Control change 45 127") deadbeef --toggle-pause ;;
        "Control change 48 127") deadbeef --next $(($data2*100/127)) ;;
        "Control change 47 127") deadbeef --prev $(($data2*100/127)) ;;
        "Control change 46 127") deadbeef --stop $(($data2*100/127)) ;;
        "Control change 41 127") pactl set-default-sink alsa_output.pci-0000_0c_00.3.analog-stereo ;;
        "Control change 40 127") pactl set-default-sink alsa_output.usb-Yamaha_Corporation_Steinberg_UR12-00.analog-stereo ;;
    esac
done
